### ISSUE TITLE
Claim Protection

### ISSUE THREAD

**Issue by corytortoise** [poggit-orphanage/FactionsPro#1]
Currently, in FactionListener.php, both block breaking and block placing protection is faulty. The plugin checks if the player who breaks the block is in the claimed area, not if the block broken is. Due to this, a player can simply stand just outside of the claimed area and break or place blocks inside the claim. I suggest this be fixed by making the plugin check if the broken or placed block is inside a plot area, rather than the player.

**Comment by Awzaw** [comment]
Well spotted, submit a PR!

**Comment by corytortoise** [comment]
I messed around with a fix a while back, but I wasn't 100% successful. I'll give it another try. :)
