### ISSUE TITLE
Faction Issue

### ISSUE THREAD

**Issue by BajanVlogs** [poggit-orphanage/FactionsPro#10]
I have a issue with factionspro plugin when i do all the {fac_rank}{fac_name} all in the purechat then go ingame and reload then talk in chat it shows as {fac_rank}{fac_name} but when i make a faction it shows my fac name like DarkUnion but when i do /f del then it shows {fac_rank}{fac_name}

**Comment by kenygamer** [comment]
@BajanVlogs Nametag will be updated once you relog.

**Comment by Panda843** [comment]
but... to be honest I don't like how PureChat handles it as well

**Comment by kenygamer** [comment]
@Panda843 It does not take care of player nametags. it translates the tags {} for displaying player information such as, the faction name.

**Comment by Panda843** [comment]
Ummm "take care of player nametags" => "do something with their nametags".

**Comment by kenygamer** [comment]
@Panda843 Understood. thanks for explaining!
#
☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by optimusprime338** [comment]
comeon its working awesome with pure chat . there is no problems lol

**Comment by Awzaw** [comment]
Did anyone test the fix I made for this?

**Comment by Panda843** [comment]
No need to test. it is fine

**Comment by Panda843** [comment]
I tried to make something of my own, though. Take a look at this : github.com/Panda843/factionsZ
