### ISSUE TITLE
[IDEA] Power/STR

### ISSUE THREAD

**Issue by Dragonblitz10** [poggit-orphanage/FactionsPro#12]
Faction starts with a configurable Power/STR
Every time a player dies they lose STR 
Every time a player kills a player they gain STR
when a new player joins they get STR
When a player leaves they lose STR
when claiming land you need a certain amount of STR (But don't lose)
/f addstr or /f addpower (if using - it will deduct)

**Comment by Panda843** [comment]
I am assuming you didn't look at the code or something because most of your suggestions have already been implemented

**Comment by Dragonblitz10** [comment]
Nah my cousin used my account to make a pointless issue sorry for any inconveniences
