### ISSUE TITLE
Could you make this version backwards comp. with A6?

### ISSUE THREAD

**Issue by Little2Epic** [poggit-orphanage/FactionsPro#17]
I don't trust A7 all too soon. It doesn't work on 1.2 or 1.0.x.

**Comment by SOF3** [comment]
And 1.2 support will never use ALPHA6 either.

**Comment by dktapps** [comment]
and alpha6 never supported 1.0.x

**Comment by Awzaw** [comment]
The main 'Release' page on Poggit only displays the latest version for each plugin right now; to find older releases you need to search specifically on the 'release' page for a plugin, or use the June 29th build.
