### ISSUE TITLE
https://timings.pmmp.io/?url=26268882

### ISSUE THREAD

**Issue by BajanVlogs** [poggit-orphanage/FactionsPro#29]
Please take a look at this and maybe fix this

**Comment by SOF3** [comment]
The database querying style definitely needs improvement, e.g. caching results. But this is quite a large change, and is probably out of scope of what @poggit-orphanage normally does (not that it shouldn't be done on poggit-orphanage, but this is not what we usually do).

**Comment by Awzaw** [comment]
The row:
`0.13%	 435.36%	  0.87 s	   217.68 ms	 0.0	       0.0k	    FactionsPro\FactionListener::onKill(PlayerDeathEvent)`

Is not contributing significantly to your server load - it only happened 4 times during your 10 minutes sample, for a total of 4 * 217ms, i.e 0.87 s which comes out as a misleading `435 Pct Tick`, but the Pct Total is only 0.13%. Still, it needs improving... I'll take a look.
