### ISSUE TITLE
Names with Spaces

### ISSUE THREAD

**Issue by Haxley** [poggit-orphanage/FactionsPro#31]
Names with Spaces can not be /f invited. I'm sure other commands after that wouldn't work either (like /f promote).

**Comment by SOF3** [comment]
Use quotes around the names.

**Comment by Haxley** [comment]
Wrapping in quotation marks does not work

**Comment by kenygamer** [comment]
String arguments have been added in PocketMine. What's wrong?

**Comment by Haxley** [comment]
Oh, which version did they add that? Running PMMP for 1.2.7. To confirm, getPlayerNameExact now works with quotation marks (string)?
