### ISSUE TITLE
how to fix it

### ISSUE THREAD

**Issue by Dearkungchannel** [poggit-orphanage/FactionsPro#38]
[Server thread/CRITICAL]: Error: "Call to a member function close() on null" (EXCEPTION) in "FactionsPro.phar/src/FactionsPro/FactionMain" at line 458
pmmp 1.2 alpha 11 build 716

**Comment by Awzaw** [comment]
I can't reproduce this - is it still happening?

**Comment by Panda843** [comment]
Looks like he deleted the factions database file while his server was running... In the end it backfired
