### ISSUE TITLE
PureChat

### ISSUE THREAD

**Issue by ManiakMCPE** [poggit-orphanage/FactionsPro#43]
I've been trying to fix this, but when I add {fac_name} or {fac_rank} it does nothing in chat. Please fix.

**Comment by Awzaw** [comment]
Have you set `default-factions-plugin: FactionsPro` in PureChat config.yml? And which version of FactionsPro are you using?

**Comment by ManiakMCPE** [comment]
Yeah, that worked. You should clarify that in the description so other idiots like me can figure it out.
