### ISSUE TITLE
Cleaner Chat

### ISSUE THREAD

**Issue by benzodoesdev** [poggit-orphanage/FactionsPro#45]
Can u perhaps add a configuration file so server owners could change the /f help list of commands format, it is quite spammy.

- Best regards Benzo

**Comment by Awzaw** [comment]
The command `/f help` displays a list of all FactionsPro commands to the player who requested it - not what I'd call "spammy"... it would be easy enough to change it to show only the commands for which the  player has permissions, or which are enabled in config, but I doubt I'll have time for that soon... feel free to make a pull request though.

**Comment by Esch16** [comment]
I agree, a hardcoded format is quite stupid, there should be a config where the specific format of a certain command will be specified by the owner.

**Comment by SOF3** [comment]
This is a slipper slope.
> A hardcoded language is stupid
> A hardcoded format is stupid
> A hardcoded command name is stupid
> A hardcoded plugin name is stupid
> A hardcoded plugin author is stupid 

Let's add an option to dynamically changed the author name!
