### ISSUE TITLE
when i did /f promote and promoted the leader isnt leader anymore

### ISSUE THREAD

**Issue by xHeraKill3r** [poggit-orphanage/FactionsPro#46]

**Comment by Esch16** [comment]
yeah that's quite stupid, you are not supposed to execute the promote/demote command on the leader. There are commands such as plead (i suppose, that passes the leadership). You can't have multiple leaders of a faction

**Comment by Awzaw** [comment]
This should now be impossible (7913bd354bf5c0ae12725c38)
