### ISSUE TITLE
Can't start a war due to factions are not enemies each other

### ISSUE THREAD

**Issue by kenygamer** [poggit-orphanage/FactionsPro#50]
The enemy system of FactionsPro is extremately bugged, as well as there are issues when trying to start a war since factions are not enemies, even though `/f enemy` was run previously.

**Comment by kenygamer** [comment]
Furthermore, there's no command to break enmity between factions. There's only a wrongly used command `/f breakalliancewith` that should only be used for faction alliances.

**Comment by kenygamer** [comment]
Furthermore, there is no command to break enmity between factions. There is only a wrongly used command `/f breakalliancewith` that should only be used for faction alliances, which is as of now used to also break enmity.

**Comment by Awzaw** [comment]
Yes it's buggy, I expect that's why the author removed it all from the beta. I presume you mean `/f enemywith <factionname>`, not just `enemy`? There doesn't appear to be any code to unset enemies... and `breakalliancewith` doesn't affect enemies either. What would you suggest?

**Comment by kenygamer** [comment]
In fact, the allies and enemies system were both failing. It is now fixed, thank you.
