### ISSUE TITLE
Cant claim the the world

### ISSUE THREAD

**Issue by ModdingTwins** [poggit-orphanage/FactionsPro#57]
when i try to claim in the world we suppose to it does not work properly.

**Comment by Awzaw** [comment]
It's working fine for me - what exactly isn't working? Have you got spaces in world names, or level.dat files that don't match the level folder name?

**Comment by Esch16** [comment]
how does it not work properly? what do you expect to happen

**Comment by splexpe** [comment]
I am having the same issue, I specified which world (world2) in the config, but when I go ingame and /f claim it says myserversprefix -> Factions Claim Worlds:

I really need this fixed asap

**Comment by Awzaw** [comment]
Can you post your config, using 'insert code'?

**Comment by splexpe** [comment]
---
MaxFactionNameLength: 15
MaxPlayersPerFaction: 30
OnlyLeadersAndOfficersCanInvite: true
OfficersCanClaim: false
ClaimingEnabled: true
PlotSize: 16
PlayersNeededInFactionToClaimAPlot: 5
PowerNeededToClaimAPlot: 300
PowerNeededToSetOrUpdateAHome: 100
PowerGainedPerPlayerInFaction: 50
PowerGainedPerKillingAnEnemy: 10
PowerGainedPerAlly: 100
AllyLimitPerFaction: 5
enable-faction-tag: true
enable-not-created-hud: true
hud-message: '&7< &drealmetro.buycraft.net &7>'
updateTag-tick: 20
faction-tag: §c❖{player} §3| §7{faction}§c❖
tag-type: scoretag
update-checker: true
TheDefaultPowerEveryFactionStartsWith: 0
EnableOverClaim: true
ClaimWorlds: world2
AllowChat: true
AllowFactionPvp: false
AllowAlliedPvp: false
defaultFactionBalance: 0
MoneyGainedPerPlayerInFaction: 20
MoneyGainedPerAlly: 50
MoneyNeededToClaimAPlot: 0
ServerName: §7Metro§3PvP
prefix: §a[§7Metro§3PvP§a]
spawnerPrices:
  skeleton: 500
  pig: 200
  chicken: 100
  iron golem: 5000
  zombie: 800
  creeper: 4000
  cow: 700
  spider: 500
  magma: 10000
  ghast: 10000
  blaze: 15000
  empty: 100
...

**Comment by Awzaw** [comment]
That's why I asked for code insert... The ClaimWorlds entry should be an array, like this if you have only one, and for multiple use commas to separate them :

`ClaimWorlds: ["world 2"]`

**Comment by splexpe** [comment]
Ohh tysm sorry for the confusion
