### ISSUE TITLE
IDEA: Adding STR

### ISSUE THREAD

**Issue by ManiakMCPE** [poggit-orphanage/FactionsPro#64]
There needs to be a command that allows console and ops to give a certain faction power. 
EX: /f addpower {factionname} [power]

**Comment by Esch16** [comment]
Normally it's not called STR, that had been my first idea when I was trying to reimplement the power system myself 3 years ago. I don't think that feature is important for now, what matters more is improving the quality of the code itself

**Comment by ManiakMCPE** [comment]
Sorry, but it kinda is important. Players need more ways to earn power. With this command, server owners can use the command in their plugins to give players power for doing certain things. For example: I have a custom made KOTH plugin that runs command when the player captures the point. If this command existed I could also reward the players with power.

**Comment by Esch16** [comment]
Yeah you are right

**Comment by Awzaw** [comment]
Very late, but I've added this to the latest dev build: https://poggit.pmmp.io/ci/poggit-orphanage/FactionsPro/FactionsPro/dev
