### ISSUE TITLE
fac-name

### ISSUE THREAD

**Issue by optimusprime338** [poggit-orphanage/FactionsPro#7]
Hey I cant get ** for owners on fac-name in chat! using with pure chat?Is there any special setting??

**Comment by Awzaw** [comment]
You should be able to set it in PureChat's config.yml:

`default-factions-plugin: FactionsPro`

**Comment by optimusprime338** [comment]
I know that but I was explain like I created factions called "test" so I should have in my prefix as "**test" and players who I invite in my factions should have like "test"  but I cant do it.

**Comment by Awzaw** [comment]
Can you try this version instead, it's more recent: https://poggit.pmmp.io/p/FactionsProBeta

**Comment by optimusprime338** [comment]
I did but fac-rank not workin on that too!!

**Comment by optimusprime338** [comment]
nvm thanks for help. this one is working awesome now . there was some problem with pure chat .. it was newest but I got a version modified version from poggit ci and its working awesome with that:)
