### ISSUE TITLE
Fatal Error when loading plugin

### ISSUE THREAD

**Issue by ZEUS1903** [poggit-orphanage/FactionsPro#76]
Fatal error: Declaration of FactionsPro\FactionMain::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, FactionsPro\Manaing $label, array $args): bool must be compatible with pocketmine\plugin\PluginBase::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool in /home/minecraft/plugins/FactionsPro/src/FactionsPro/FactionMain.php on line 31

**Comment by SOF3** [comment]
You're using a modified version.
